export const resumeSections = {
  personalInfo: [
    {
      key: "fullName",
      label: "Full Name",
      type: "text",
      required: true,
      maxLength: 100,
      placeholder: "Enter your full name",
    },
    {
      key: "email",
      label: "Email",
      type: "email",
      required: true,
      pattern: "^[\\w\\.-]+@([\\w-]+\\.)+[\\w-]{2,4}$",
      placeholder: "Enter your email",
    },
    {
      key: "phone",
      label: "Phone",
      type: "tel",
      pattern: "^\\+?[1-9]\\d{1,14}$",
      placeholder: "Enter your phone number",
    },
    {
      key: "address",
      label: "Address",
      type: "text",
      maxLength: 200,
      placeholder: "Enter your address",
    },
    {
      key: "linkedin",
      label: "LinkedIn",
      type: "url",
      pattern: "^https?://(www\\.)?linkedin\\.com/.*$",
      placeholder: "Enter your LinkedIn profile URL",
    },
    {
      key: "github",
      label: "GitHub",
      type: "url",
      pattern: "^https?://(www\\.)?github\\.com/.*$",
      placeholder: "Enter your GitHub profile URL",
    },
    {
      key: "objective",
      label: "Objective",
      type: "textarea",
      maxLength: 500,
      placeholder: "Enter your career objective",
    },
  ],
  education: [
    {
      key: "degree",
      label: "Degree",
      type: "text",
      required: true,
      maxLength: 100,
      placeholder: "e.g., Bachelor of Science in Computer Science",
    },
    {
      key: "institution",
      label: "Institution",
      type: "text",
      required: true,
      maxLength: 100,
      placeholder: "e.g., University of Example",
    },
    {
      key: "year",
      label: "Year",
      type: "text",
      required: true,
      pattern: "^\\d{4}$",
      placeholder: "e.g., 2023",
    },
    {
      key: "percentage",
      label: "Percentage",
      type: "number",
      min: 0,
      max: 100,
      placeholder: "e.g., 85",
    },
  ],




   experience: [
    { key: "company_name", label: "Company Name", type: "text", required: true, maxLength: 255 },
    { key: "role", label: "Role", type: "text", required: true, maxLength: 255 },
    { key: "employee_id", label: "Emp Id", type: "text", required: true, maxLength: 255 },
    { key: "duration", label: "Duration", type: "text", required: true, maxLength: 255, placeholder: "e.g., Jan 2020 - Dec 2022" },
    { key: "location", label: "Location", type: "text", required: true, maxLength: 255 },
    { key: "description", label: "Description", type: "textarea", maxLength: 1000 }, // Optional, maps to `experience`
  ],
  projects: [
    {
      key: "title",
      label: "Project Title",
      type: "text",
      required: true,
      maxLength: 100,
      placeholder: "e.g., E-commerce Website",
    },
    {
      key: "description",
      label: "Description",
      type: "textarea",
      required: true,
      maxLength: 500,
      placeholder: "Describe the project",
    },
    {
      key: "technologies",
      label: "Technologies",
      type: "text",
      maxLength: 200,
      placeholder: "e.g., React, Node.js, MongoDB",
    },
    {
      key: "link",
      label: "Project Link",
      type: "url",
      pattern: "^https?://.*$",
      placeholder: "e.g., https://example.com",
    },
  ],
  skills: [
    {
      key: "skill",
      label: "Skill",
      type: "text",
      required: true,
      maxLength: 50,
      placeholder: "e.g., JavaScript",
    },
    {
      key: "proficiency",
      label: "Proficiency",
      type: "select",
      required: true,
      placeholder: "Select proficiency level",
      options: [
        { value: "Beginner", label: "Beginner" },
        { value: "Intermediate", label: "Intermediate" },
        { value: "Advanced", label: "Advanced" },
      ],
    },
  ],
  certifications: [
    {
      key: "name",
      label: "Certification Name",
      type: "text",
      required: true,
      maxLength: 100,
      placeholder: "e.g., AWS Certified Developer",
    },
    {
      key: "authority",
      label: "Issuing Authority",
      type: "text",
      required: true,
      maxLength: 100,
      placeholder: "e.g., Amazon Web Services",
    },
    {
      key: "year",
      label: "Year",
      type: "text",
      required: true,
      pattern: "^\\d{4}$",
      placeholder: "e.g., 2023",
    },
  ],
  achievements: [
    {
      key: "title",
      label: "Achievement Title",
      type: "text",
      required: true,
      maxLength: 100,
      placeholder: "e.g., Won Hackathon 2023",
    },
    {
      key: "description",
      label: "Description",
      type: "textarea",
      required: true,
      maxLength: 500,
      placeholder: "Describe the achievement",
    },
  ],
};